PROJECT=Taller2
TEX=pdflatex
BIBTEX=bibtex
BUILDTEX=$(TEX) $(PROJECT).tex

all: clean comp open clean

comp:
	$(BUILDTEX)
#	$(BIBTEX) $(PROJECT)
#	$(BUILDTEX)
#	$(BUILDTEX)

clean:
	rm -f *.dvi *.log *.bak *.aux *.bbl *.blg *.idx *.ps *.eps *.toc *.out *~

open: clean
	open $(PROJECT).pdf
